{
 "title": "CITA Node Info Dashboard",
 "description": "CITA Node Info Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(Node_Get_ServiceStatus,job)"
    }
   },
   {
    "name": "node_id",
    "label": "NodeID",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\"},NodeID) "
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "端口",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
    }
   },
   {
    "name": "ChainName",
    "label": "ChainName",
    "query": {
     "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},ChainName)"
    }
   },
   {
    "name": "Operator",
    "label": "Operator",
    "query": {
     "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Operator)"
    }
   },
   {
    "name": "TokenName",
    "label": "TokenName",
    "query": {
     "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenName)"
    }
   },
   {
    "name": "TokenSymbol",
    "label": "TokenSymbol",
    "query": {
     "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenSymbol)"
    }
   },
   {
    "name": "Version",
    "label": "Version",
    "query": {
     "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Version)"
    }
   },
   {
    "name": "GenesisBlockNumberHash",
    "label": "GenesisBlockNumberHash",
    "query": {
     "query": "label_values(Node_Get_GenesisBlockNumberDetails{instance=~'$node:$port'},GenesisBlockNumberHash)"
    }
   },
   {
    "name": "LastBlockNumberHash",
    "label": "LastBlockNumberHash",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumberDetails,LastBlockNumberHash) "
    }
   },
   {
    "name": "node_dir",
    "label": "Node Dir",
    "query": {
     "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDir) "
    }
   },
   {
    "name": "ConsensusStatus",
    "label": "ConsensusStatus",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},ConsensusStatus) "
    }
   },
   {
    "name": "SoftVersion",
    "label": "SoftVersion",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},SoftVersion) "
    }
   },
   {
    "name": "HostPlatform",
    "label": "HostPlatform",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostPlatform) "
    }
   },
   {
    "name": "HostName",
    "label": "HostName",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostName) "
    }
   },
   {
    "name": "NodeAddress",
    "label": "NodeAddress",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeAddress) "
    }
   },
   {
    "name": "NodeIP",
    "label": "NodeIP",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeIP) "
    }
   },
   {
    "name": "NodePort",
    "label": "NodePort",
    "query": {
     "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodePort) "
    }
   },
   {
    "name": "MaxBlockNumber",
    "label": "MaxBlockNumber",
    "query": {
     "query": "query_result(max(Node_Get_LastBlockNumber{job=\"$job\"}))"
    }
   },
   {
    "name": "timeRange",
    "label": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "链基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<center>\n<h2>名称</h2>\n<br><br>\n<h1>$ChainName</h1>\n</center>"
   }
  },
  {
   "title": "创世块时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_GenesisBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (Node_Get_GenesisBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "创世区块hash",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<center>\n<br>\n<h2>$GenesisBlockNumberHash</h2>\n</center>"
   }
  },
  {
   "title": "协议版本",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": {
    "content": "<center>\n<br>\n<h2>$Version</h2>\n</center>"
   }
  },
  {
   "title": "运营方",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": {
    "content": "<center>\n<br>\n<h2>$Operator</h2>\n</center>"
   }
  },
  {
   "title": "Token符号",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": {
    "content": "<center>\n<br>\n<h2>$TokenSymbol</h2>\n</center>"
   }
  },
  {
   "title": "经济模式",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_ChainInfo{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  { "title": "链信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "最新区块号 [ $ChainName ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Node_Get_LastBlockNumber{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "区块quota限制 [ $ChainName ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Node_Get_BlockQuotaLimit{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "区块高度 [ $ChainName ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "共识节点数 [ $ChainName ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Node_Get_ChainNodes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Quota价值 [ $ChainName ]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Node_Get_QuotaPrice{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "共识节点投票比",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_VoteNode{job=\"$job\",NodeID=\"$node_id\"}[$__range]) * 100",
     "legendFormat": "{{Voter}}"
    }
   ]
  },
  {
   "title": "共识节点投票数 [ Block ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Block_Vote_Number{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  { "title": "节点信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 19 },
   "options": {
    "content": "<center>\n<div align=\"left\">\n<h2>Node ID : <span>$node_id</span></h2>\n<h2>Node JSON-RPC : <span>$NodeIP:$NodePort</span></h2>\n</div>\n</center>"
   }
  },
  {
   "title": "区块号",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "最新区块号",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "上一区块时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (Node_Get_LastBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "最新区块提案节点",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_CheckProposer{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "最新区块交易数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "上一区块间隔",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_BlockDifference{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "平均区块间隔",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}[$__range])"
    }
   ]
  },
  {
   "title": "区块交易数历史",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "区块间隔",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "最新1分钟TPS",
   "type": "stat",
   "description": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$instance\"}[1m]) / 60",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}[1m]) / 60"
    }
   ]
  },
  {
   "title": "Quota信息",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockQuotaLimit{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Block Limit"
    },
    {
     "expr": "Node_Get_LastBlockNumberQuotaUsed{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Quota Used"
    },
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Block Number"
    }
   ]
  },
  {
   "title": "节点类型",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$ConsensusStatus" }
   ]
  },
  {
   "title": "节点链上地址",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 38 },
   "options": {
    "content": "<center>\n<br>\n<h2>$NodeAddress</h2>\n</center>"
   }
  },
  {
   "title": "本地投票历史",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "1" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LocalVoter{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "硬盘使用情况",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} * 1024",
     "legendFormat": "Node Dir Size Used by [ node : $node_id ]"
    },
    {
     "expr": "Node_Get_DiskInfo_UsedSize{job=\"$job\",instance=\"$node:$port\"} - (Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} * 1024)",
     "legendFormat": "Other Used"
    },
    {
     "expr": "Node_Get_DiskInfo_FreeSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "节点目录磁盘使用情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} - Node_Get_DirInfo_DataFileSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeDir}}/logs"
    },
    {
     "expr": "Node_Get_DirInfo_DataFileSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeDir}}/data"
    }
   ]
  },
  {
   "title": "软件版本",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 48 },
   "options": {
    "content": "<center>\n<br>\n<h5>$SoftVersion</h5>\n</center>"
   }
  },
  {
   "title": "节点域名",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 48 },
   "options": {
    "content": "<center>\n<br>\n<h3>$HostName</h3>\n</center>"
   }
  },
  {
   "title": "连接节点数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Node_Get_NodePeers{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "节点系统",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 52 },
   "options": {
    "content": "<center>\n<br><br>\n<h3>$HostPlatform</h3>\n</center>"
   }
  }
 ]
}