{
 "title": "Process Info Dashboard",
 "description": "Process Info Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(up{job=~'process-exporter'},instance)"
    }
   },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_thread_cpu_seconds_total{instance=~'$node.+'},groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "进程数量 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{instance=~'$node.+',groupname=~\"$processes\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "进程CPU使用 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(groupname)(rate(namedprocess_namegroup_thread_cpu_seconds_total{instance=~'$node.+',groupname=~\"$processes\"}[$interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "网络读速率 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{instance=~'$node.+',groupname=~\"$processes\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "网络写速率 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=~'$node.+',groupname=~\"$processes\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "使用内存 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~'$node.+',groupname=~\"$processes\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "虚拟内存 ( $node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~'$node.+',groupname=~\"$processes\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}