{
 "title": "RabbitMQ Dashboard",
 "description": "RabbitMQ Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(up{job=~'rabbitmq-exporter'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ服务状态",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_up{instance=~'$node.+'}"
    }
   ]
  },
  {
   "title": "正在运行中的节点数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~'$node.+'}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "使用中的交换机数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchanges{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "通道数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channels{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:channels"
    }
   ]
  },
  {
   "title": "消费者数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_consumers{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:consumers"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:connections"
    }
   ]
  },
  {
   "title": "队列数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queues{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "服务中消息数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "队列中消息数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=~'$node.+'}",
     "legendFormat": "{{queue}}:{{durable}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~'$node.+'}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "文件描述符打开数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~'$node.+'}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Socket连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~'$node.+'}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}