global:
  resolve_timeout: 5m
  smtp_from: 'smtpEmail'
  smtp_smarthost: 'smtpHost'
  smtp_auth_username: 'smtpEmail'
  smtp_auth_password: '112a47#4a3.af9'
  smtp_require_tls: false
route:
  group_by: [ 'alertname' ]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 2h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'alerterEmails'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: [ 'alertname', 'dev', 'instance' ]